spring:
  application:
    name=My-First-Web-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_first_web_app?useTimezone=true&serverTimezone=UTC
    username: root
    password: 235689
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
     root: WARN
   # dev.Anderson.My_First_Web_App: DEBUG